# Generated by Django 4.0 on 2022-02-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khana', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
