# Generated by Django 4.0 on 2022-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khana', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=200)),
                ('blog_details', models.CharField(max_length=200)),
                ('blog_price', models.CharField(max_length=500)),
                ('blog_image', models.FileField(upload_to='blog_image')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
