# Generated by Django 4.0 on 2022-02-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khana', '0004_blogs_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_price',
        ),
    ]
