# Generated by Django 4.0 on 2022-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_details', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=500)),
                ('product_image', models.FileField(upload_to='product_image')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
