# Generated by Django 4.0 on 2022-02-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_details', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=500)),
                ('product_image', models.FileField(upload_to='product_image')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Mbooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('your_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('phone_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
            options={
                'db_table': 'boking_gymequipment',
            },
        ),
    ]
